FACILITIES = {
        "ADM": {
            "Cinema Room (ADM)": 9,
            "Viewing Corner": 46
        },
        "BL": {
            "Language Learning Room 1": 11,
            "Language Learning Room 2": 12,
            "Language Learning Room 3": 13,
            "Language Learning Room 4": 14,
            "Language Learning Room 5": 15,
            "Pod 1": 23,
            "Pod 2": 24,
            "Pod 3": 25,
            "Pod 4": 26,
            "Pod 5": 27,
            "Pod 6": 28,
            "Pod 7": 29,
            "Study Room A": 32,
            "Study Room B": 33,
            "Study Room C": 34,
            "Study Room D": 35,
            "Study Room E": 36,
            "Study Room F": 37,
            "Study Room G": 38,
            "Study Room H": 39,
            "Study Room I": 40,
            "Study Room J": 41,
            "Study Room K": 42,
            "Study Room L": 43,
            "Study Room M": 44,
            "Study Room N": 45,
        },
        "LWN": {
            "Artwood (Mirroring TV)": 69,
            "Butler (No Mirroring TV)": 72,
            "Griffin Booth 01 (no PC)": 56,
            "Griffin Booth 02": 63,
            "Griffin Booth 03": 58,
            "Griffin Booth 04": 59,
            "Griffin Booth 05": 60,
            "Griffin Booth 06": 61,
            "Griffin Booth 07": 62,
            "Griffin Booth 08": 57,
            "Griffin Booth 09": 64,
            "Griffin Booth 10": 65,
            "Griffin Booth 11": 66,
            "Griffin Booth 12 (no PC)": 67,
            "Le Guin (Mirroring TV)": 68,
            "LWN Pod 1 (LCD TV)": 16,
            "LWN Pod 2 (LCD TV)": 17,
            "LWN Pod 3 (LCD TV)": 18,
            "LWN Pod 4 (SMART Board not available)": 19,
            "LWN Pod 5 (SMART Board)": 20,
            "LWN Pod 6 (SMART Board)": 21,
            "LWNL Recording Room": 31,
            "Rest Pod": 76,
            "Tardis": 74,
            "Tiptree (Mirroring TV)": 70,
            "Wilhem (Mirroring TV)": 71
        }
    }